### ISSUE TITLE
name/value variable with group in job crashes - there are too many simple/complex combinations

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/AzurePipelinesToGitHubActionsConverter#151]
Multiple issues have exposed the weaknesses of the current process. It's time to pivot and find a better way to extract individual jobs out of Azure Pipelines, normalize or process them, and then stitch the GitHub action back together. This is a fairly major change to the underlying processing, but should appear minor to the end user (i.e. the API shouldn't change and this should be a minor version increment).

There are multiple parts to this issue:

1. [x] Similar to [steps](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/blob/764a63b449a067c7c745a80d883f684397dadc79/src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs#L176), create an individual processing for jobs. #153 
    1. [x] ensure that job variations can be handled (Variables)
2. [x] Rework the entire processing to work through three steps #154 
    1. [x] extract the structure
    2. [x] process stages/jobs
    3. [x] put everything back together again
3. [x] Similar to step 1, but for stages, ensuring we have all of the edge cases handled.

**Comment by samsmithnz** [comment]
I think it's time to find a way to extract individual jobs out of Azure Pipelines, normalize or process them, and then stitch the GitHub action back together. This is a fairly major change to the underlying processing, but should appear minor to the end user (i.e. the API shouldn't change and this should be a minor version increment). 

It's dirty, but the best way to start this is probably to look for the beginning of a "job", and then split the document apart to process it. This is helped because most YAML files are less than a couple hundred lines long - performance will never really be a concern.

**Comment by f2calv** [comment]
I have also been thinking about splitting the parsing of the entire YAML doc into chunks, and because dealing all the different formatting variants/options is too much of a mind bender.
So basically,
1. read in the YAML
2. split out the following (and possibly split them out again further);
  - Triggers
  - Variables
  - Stages/Jobs/Steps (and possibly split this further)
  - Pools/Depends/Containers/etc...
3. Parse the separate chunks

OR

Another approach would be standardise the YAML format, i.e. perform a pre-parse/modification step - convert all nodes into the most 'complicated' format - but which will allow for less use of Generics further on...

I probably haven't explained any of that very well. :)

**Comment by samsmithnz** [comment]
Makes perfect sense to me. I'm thinking a combination of both approaches, taking the best of both.

1. I'm started some of this already (it's how I avoided the 16 combinations), in the [CleanYamlBeforeDeserialization](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/blob/764a63b449a067c7c745a80d883f684397dadc79/src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs#L225) function, where I convert simple triggers, pools, demands, dependson, environment, and tags, as well as fix reserved variable names (e.g. Environment).

2. Extract the jobs, as then there is just one variable format, one pool format, with a combination of cleaning/converting the variations to one complex one, and then serializing the job, should simplify the whole process.
